#!/usr/bin/env bash
#Configure ngnix so the http response contails a custom header

# Install Nginx if not already installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get update
    sudo apt-get -y install nginx
fi

# Configure custom header
echo 'server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
        add_header X-Served-By $hostname; # Add custom header with hostname
    }
}' | sudo tee /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

