#!/usr/bin/env bash
#HAProxy configuration

# Install HAProxy
sudo apt update
sudo apt install -y haproxy

# Backup the original HAProxy configuration file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<'EOF'
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server 444725-web-01 107.22.145.62:80 check
    server 444725-web-02 54.84.201.74:80 check
EOF

# Enable HAProxy as a service
sudo systemctl enable haproxy

# Restart HAProxy to apply changes
sudo systemctl restart haproxy

