#!/usr/bin/env bash
#Instal and configure HAproxy

# Update package lists
sudo apt-get update

# Install HAproxy if not already installed
sudo apt-get install -y haproxy

# Configure HAproxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Restart HAproxy to apply changes
sudo service haproxy restart

exit 0
