#!/usr/bin/env bash
# configures a server to listening on port 80 of all server's active IPv4 IPs

# Check if Nginx is listening on port 80
netstat -tuln | grep ":80" > /dev/null
if [ $? -ne 0 ]; then
    echo "Nginx is not listening on port 80. Restarting Nginx..."
    sudo systemctl restart nginx
    sleep 2  # Wait for Nginx to restart
    echo "Nginx restarted."
else
    echo "Nginx is already listening on port 80."
fi


# Check if Nginx returns HTTP 200 on port 80
curl -s -o /dev/null -w "%{http_code}" http://localhost/ > /tmp/nginx_status_code
status_code=$(cat /tmp/nginx_status_code)

if [ $status_code -eq 200 ]; then
    echo "Nginx returned HTTP 200 on port 80."
else
    echo "Nginx did not return HTTP 200 on port 80. Status code: $status_code"
fi