#!/usr/bin/env bash
# Create a backup of the current /etc/hosts file

cp /etc/hosts ~/hosts.new

# Use sed to modify the backup file (hosts.new)
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

# Overwrite the original /etc/hosts file with the modified one
cp -f ~/hosts.new /etc/hosts

