#!/bin/bash

echo "Active IPv4 IPs on the machine:"
echo "--------------------------------"

# Use the ifconfig command to get information about network interfaces
ifconfig -a | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | grep -vE "^127\.0\.0\.1"

# Alternatively, you can use the following command for newer systems using the 'ip' command:
# ip -4 address show | awk '/inet/ {print $2}' | cut -d'/' -f1

